In [ ]:
import torch

from hakken_ml_toolkit.losses import (
    BCEWithLogitsLoss,
    BCEWithLogitsLossConfig,
    MarginRankingLoss,
    MarginRankingLossConfig,
)

# Demo 1: BCEWithLogitsLoss

In [2]:
# Create dummy data
logits = torch.randn(3, 2)  # 3 samples, 2 classes
targets = torch.randint(0, 2, (3, 2))  # Binary targets

# Initialize loss function
bce_config = BCEWithLogitsLossConfig()
bce_loss = BCEWithLogitsLoss(bce_config)

# Compute loss
loss = bce_loss.compute(logits, targets)

print(f"Logits:\n{logits}")
print(f"Targets:\n{targets}")
print(f"BCE Loss:\n{loss}")

Logits:
tensor([[-0.3787, -0.5992],
        [ 3.1178,  2.8319],
        [ 0.0161,  0.0549]])
Targets:
tensor([[1, 1],
        [0, 1],
        [1, 0]])
BCE Loss:
tensor([6.5617])


# Demo 2: MarginRankingLoss


In [4]:
# Create dummy data
positive_scores = torch.randn(3, 1)  # 3 samples
negative_scores = torch.randn(3, 1)  # 3 samples

# Initialize loss function
margin_config = MarginRankingLossConfig(margin=0.5)
margin_loss = MarginRankingLoss(margin_config)

# Compute loss
loss = margin_loss.compute(positive_scores, negative_scores)

print(f"Positive Scores:\n{positive_scores}")
print(f"Negative Scores:\n{negative_scores}")
print(f"Margin Ranking Loss:\n{loss}")

Positive Scores:
tensor([[ 1.2644],
        [-0.0109],
        [-0.4782]])
Negative Scores:
tensor([[-1.2080],
        [ 2.4478],
        [ 0.2063]])
Margin Ranking Loss:
tensor([4.1431])


# Demo 3: Simple Training Loop

In [5]:
# Create a simple model
class SimpleModel(torch.nn.Module):
    def __init__(self, input_dim, output_dim):
        super().__init__()
        self.linear = torch.nn.Linear(input_dim, output_dim)

    def forward(self, x):
        return self.linear(x)


# Set up model and optimizer
model = SimpleModel(10, 2)
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

# Create dummy dataset
X = torch.randn(100, 10)
y = torch.randint(0, 2, (100, 2))

# Training loop
bce_loss = BCEWithLogitsLoss(BCEWithLogitsLossConfig())

for epoch in range(5):
    optimizer.zero_grad()

    # Forward pass
    outputs = model(X)
    loss = bce_loss.compute(outputs, y)

    # Backward pass and optimize
    loss.mean().backward()
    optimizer.step()

    print(f"Epoch {epoch + 1}, Loss: {loss.mean().item():.4f}")

print("\nTraining complete!")

Epoch 1, Loss: 143.4451
Epoch 2, Loss: 142.1656
Epoch 3, Loss: 140.9466
Epoch 4, Loss: 139.7888
Epoch 5, Loss: 138.6918

Training complete!
